apiVersion: batch/v1
kind: Job
metadata:
  name: feast-sync
  labels:
    app: feast-sync
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: feast-sync
    spec:
      restartPolicy: Never

      initContainers:
        - name: init-minio-feast-buckets
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc alias set myminio http://minio-service:9000 minioadmin minioadmin && \
              mc mb myminio/feast-registry || true && \
              mc mb myminio/feast-offline || true

      containers:
        - name: feast-sync-worker
          image: romangoldur/feast-repo:v1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "[INFO] =========================================="
              echo "[INFO] DEBUT DU JOB FEAST-SYNC - $(date -u)"
              echo "[INFO] =========================================="
              
              cd /feast/repo
              
              echo "[INFO] [1/2] Execution de 'feast apply'..."
              feast apply
              
              TARGET_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S" -d "-7 days")
              echo "[INFO] [2/2] Execution de 'feast materialize-incremental' ($TARGET_DATE)..."
              feast materialize-incremental "$TARGET_DATE"
              
              echo "[INFO] =========================================="
              echo "[INFO] JOB FEAST-SYNC TERMINE AVEC SUCCES"
              echo "[INFO] =========================================="
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"
            - name: FEAST_S3_ENDPOINT_URL
              value: "http://minio-service:9000"
            - name: AWS_ENDPOINT_URL
              value: "http://minio-service:9000"