apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi # Doit être inférieur ou égal à la capacité du PV
  storageClassName: manual # Crucial : force la liaison directe avec dataset-pv