apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-sync
  labels:
    app: dataset-sync
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 900
  template:
    metadata:
      labels:
        app: dataset-sync
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: create-dvc-bucket
          image: minio/mc
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          command:
            - /bin/sh
            - -c
            - |
              # Utilisation du DNS interne K8s : minio-service:9000
              mc alias set myminio http://minio-service:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb --ignore-existing myminio/dvc-store

        - name: init-dataset-dir
          image: romangoldur/a62-sync:v13
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Initialisation et ouverture des droits du volume Linux..."
              mkdir -p /workspace/data
              chmod -R 777 /workspace/data
              echo "[INIT] Volume prêt pour DVC."
          volumeMounts:
          - name: dataset-volume
            mountPath: /workspace/data

      containers:
      - name: sync-worker
        image: romangoldur/a62-sync:v13
        imagePullPolicy: Always

        securityContext:
          runAsUser: 0
          runAsGroup: 0

        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        - name: DVC_NO_SCM
          value: "1"

        volumeMounts:
        - name: dataset-volume
          mountPath: /workspace/data

        command: ["python", "/app/sync.py"]

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: dataset-pvc
